routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ArticleController@index');
Route::resource('/articles','ArticleController');



 

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

//use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;


class Article extends Eloquent
{
    protected $connection = 'mongodb';
	protected $collection = 'article';  
}

app/Mongodb.php
<?php

namespace App; 
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;


class Mongodb extends Eloquent 
{  
	protected $connection = 'mongodb';
	protected $collection = 'users';  
	 
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\Article;
use Image;
use Purifier;
use Auth;
use Session;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all()->sortByDesc("created_at");;
        return view('articles.index')->withArticles($articles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {  
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //


     $this->validate($request, array(
        'title'         => 'required|max:255',
        'body'          => 'required',
        'file' => 'max:2048|mimes:jpeg,png' 
        ));
      // store in the database




     $art = new Article();
     $art->title = Purifier::clean($request->title);  
     $art->body = Purifier::clean($request->body);
     $art->authname = Auth::user()->name;
     $art->authid = Auth::user()->id;
     if ($request->hasFile('file')) {
        $image = $request->file('file');
        $filename =date('Ymd').time() . '.' . $image->getClientOriginalExtension();
        $location = public_path('images/'); 
        $request->file('file')->move($location,$filename);
        $art->image = $filename;
    }
    else
    {
        $art->image = '';
    }
    $art->save(); 
        //$post->tags()->sync($request->tags, false);
    Session::flash('success', 'The article was successfully save!');
    return redirect()->route('articles.show', $art->id); 

}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id);
        
        return view('articles.show')->withArticle($article);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        return view('articles.update')->withArticle($article);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

     $this->validate($request, array(
        'title'         => 'required|max:255',
        'body'          => 'required',
        'file' => 'max:2048|mimes:jpeg,png' 
        ));
  

     $art = Article::find($id);
     $art->title = Purifier::clean($request->title);  
     $art->body = Purifier::clean($request->body);
     $art->authname = Auth::user()->name;
     $art->authid = Auth::user()->id;
 

     if ($request->hasFile('file')) 
     {
        $image = $request->file('file');
        $filename =date('Ymd').time() . '.' . $image->getClientOriginalExtension();
        $location = public_path('images/'); 
        $request->file('file')->move($location,$filename);
        $art->image = $filename;
    }
    $art->save(); 
        //$post->tags()->sync($request->tags, false);
    Session::flash('success', 'The article was successfully save!');
    return redirect()->route('articles.show', $art->id); 
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $art = Article::find($id);
        $art->delete(); 
        return redirect()->route('articles.index'); 
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MongoController.php
<?php

namespace App\Http\Controllers;
use DB;
use App\Article;


class MongoController extends Controller
{ 
	public function index() 
	{ 
		//return "sdfadf";
		$newart = new Article();
		$newart->title = 'test 2';
		$newart->content = 'test content 2';
		$newart->save();


		$users = DB::connection('mongodb')->collection('article')->get();
		return $users;
	} 
}

resources/views/article.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @if (Auth::check())
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ url('/login') }}">Login</a>
                        <a href="{{ url('/register') }}">Register</a>
                    @endif
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Article
                </div>
 
            </div>
        </div>
    </body>
</html>

resources/views/articles/create.blade.php
@extends('layouts.app')
@section('content')
@section('page_title','Create New One')

 

<form action={{url('articles')}} method="post" enctype="multipart/form-data">

	<div class="row">
		<div class="col-md-8">
			<div class="form-group">
				<label for="title">Title:</label>
				<input name="title" type="text" class="form-control" id="title" placeholder="">
			</div> 

			<div class="form-group">
				<label for="body">Body</label>
				<textarea name="body" class="form-control" id="body" rows="20"></textarea>
			</div>

		</div>

		<div class="col-md-4  text-center container-fluid"></br></br></br>
			<div class="form-group"> 
				<img id="articleimg" src="/images/default_product.png" class="img-thumbnail">
				</br></br>
				<span class="btn btn-primary text-center" onclick="btn_select_file()"">Browse Image</span>
			</div>
		</div>

		<div class="col-md-12">
			<button type="submit" class="btn btn-success" >Submit</button>
			<input type="hidden" name="_token" value="{{{ csrf_token() }}}" />
			<input id="file" name="file" type="file" style="display: none;"  onchange="onFileSelected()"" accept="image/*" >
		</div>
	</div>
</form>

 
        <script type="text/javascript" src="/js/articles.js"></script>


        @endsection

resources/views/articles/index.blade.php
@extends('layouts.app')
@section('content')
@section('page_title','Home')


@foreach ($articles as $art)

<div class="panel panel-default">
  <div class="panel-heading list-group-item-heading">
   
      <div class="row">
        <div class="col-md-11 col-xs-11"> <a href="{{url('articles')}}/{{$art->id}}"><h4><strong>{{ strip_tags($art->title)}}</strong></h4></a></div>
        @if(!Auth::guest()) 
          @if(Auth::user()->id == $art->authid) 
            <form action="{{ route('articles.destroy', $art->id) }}" method="POST" onsubmit= "return confirm('Do you really delete this one?');">
            <input type="hidden" name="_method" value="DELETE"/>
            <input type="hidden" name="_token" value="{{ csrf_token() }}" /> 
            <a class="btn btn btn-primary" href="{{route('articles.edit',['id' => $art->id])}}">
               <i class="glyphicon glyphicon-edit"></i>
            </a>
            <button type="submit" class="delete btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
            </form>
          @endif
        @endif
      </div>
  </div>
<div class="panel-body">
  {{substr(strip_tags($art->body),0,500)}}{{strlen($art->body)>500 ? '...':''}}
</div>
<div class="panel-footer">
   {{$art->authname}} Publish {{$art->created_at->diffForHumans()}} 
</div>
</div>
<script type="text/javascript" src="/js/articles.js"></script>
@endforeach
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')
@section('content')
@section('page_title','Read The Articles')


<div class="jumbotron">
	<h2>  {{ strip_tags($article->title) }} </h2>  
	 <p>{{$article->authname}} Publish {{$article->created_at->diffForHumans()}}</p>
	@if(!Auth::guest()) 
		@if(Auth::user()->id == $article->authid)
			<form action="{{ route('articles.destroy', $article->id) }}" method="POST" onsubmit= "return confirm('Do you really delete this one?');">
            <input type="hidden" name="_method" value="DELETE"/>
            <input type="hidden" name="_token" value="{{ csrf_token() }}" /> 
            <a class="btn btn-primary" href="{{  url('articles') }}/{{$article->id}}/edit">
				<i class="glyphicon glyphicon-edit"></i>
			</a>
            <button type="submit" class="delete btn btn-danger"><i class="glyphicon glyphicon-trash"></i></button>
            </form>
		@endif
		@endif    
</div>

<div class="container">
	<div class="row">
		@if(empty($article->image))
		<div class="col-md-12">{!! nl2br(($article->body)) !!} </div>
		@else
		<div class="col-md-8">{!!nl2br(($article->body))!!} </div>
		<div class="col-md-4  text-center container-fluid">
			<img class="img-rounded img-responsive" src="{{URL::asset('/images/'.$article->image)}}">
		</div>
		@endif 
		
		
	</div>
</div> 
@endsection

resources/views/articles/update.blade.php
@extends('layouts.app')
@section('content')
@section('page_title','Update The Article')

<form action={{route('articles.update',['id' => $article->id])}} method="POST" enctype="multipart/form-data">
	<input type="hidden" name="_token" value="{{ csrf_token() }}">
	<input name="_method" type="hidden" value="PUT">

	<div class="jumbotron">
		<input name="title" type="text" class="form-control input-lg" id="title" placeholder="" value="{{ strip_tags($article->title)}}"></input>  
		<p>{{$article->authname}}</p>
		@if(!Auth::guest()) 
		@if(Auth::user()->id == $article->authid)
		<button type="submit" class="btn btn-success" ><i class="glyphicon glyphicon-ok"></i></button>
		<a class="btn btn-danger" href="{{route('articles.destroy',['id' => $article->id])}}">
			<i class="glyphicon glyphicon-remove"></i>
		</a> 
		@endif
		@endif    
	</div>

	<div class="container">
		<div class="row">

			<div class="col-md-8">
			<textarea name="body" class="form-control" id="body" rows="20">{{strip_tags($article->body) }}</textarea> 
			</div>
			<div class="col-md-4  text-center container-fluid">
				<img id="articleimg" class="img-rounded img-responsive" src="{{empty($article->image)?"/images/default_product.png":URL::asset('/images/'.$article->image)}}"></br></br>
				<span class="btn btn-primary text-center" onclick="btn_select_file()">Browse Image</span>
				<input id="file" name="file" type="file" style="display: none;"  onchange="onFileSelected()"" accept="image/*" >
			</div>
		</div>
	</div> 
</form>
<script type="text/javascript" src="/js/articles.js"></script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Simple Blog | @yield('page_title')</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>
    <body>



      <!--bootstrap nav bar-->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Simple Blog</a>
            @if (!Auth::guest())
            <a class="navbar-brand" href="{{route('articles.create')}}">Create New</a>
            @endif
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
             <!-- <li class="active"><a href="/">Link <span class="sr-only">(current)</span></a></li>
             <li><a href="#">Link</a></li> -->
           </ul>
           
           <ul class="nav navbar-nav navbar-right">
            <ul class="nav navbar-nav navbar-right">
              <!-- Authentication Links -->
              @if (Auth::guest())
              <li><a href="{{ route('login') }}">Login</a></li>
              <li><a href="{{ route('register') }}">Register</a></li>
              @else
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <ul class="dropdown-menu" role="menu">
                  <li>
                    <a href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    Logout
                  </a>

                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                  </form>
                </li>
              </ul>
            </li>
            @endif
          </ul>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  

  <div class="container">

    @if (Session::has('success'))
    
    <div class="alert alert-success" role="alert">
      <strong>Success:</strong> {{ Session::get('success') }}
    </div>

    @endif

    @if (count($errors) > 0)

    <div class="alert alert-danger" role="alert">
      <strong>Errors:</strong>
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach  
      </ul>
    </div>

    @endif


    @yield('content') 
  </div>


  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> 
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

resources/views/maincontainer.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Simple Blog | @yield('page_title')</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    </head>
    <body>



      <!--bootstrap nav bar-->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
              <li><a href="#">Link</a></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
              <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())
                <li><a href="{{ route('login') }}">Login</a></li>
                <li><a href="{{ route('register') }}">Register</a></li>
                @else
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <ul class="dropdown-menu" role="menu">
                    <li>
                      <a href="{{ route('logout') }}"
                      onclick="event.preventDefault();
                      document.getElementById('logout-form').submit();">
                      Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                    </form>
                  </li>
                </ul>
              </li>
              @endif
            </ul>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    

    <div class="container">
     @yield('content') 
   </div>


   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> 
   <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
 </body>
 </html>

resources/views/test.blade.php
<?php
ini_set('display_errors', 1);

try {

    $mng = new MongoDB\Driver\Manager("mongodb://localhost:27017");
    $query = new MongoDB\Driver\Query([]); 
     
    $rows = $mng->executeQuery("simple_store.users", $query);
    
    foreach ($rows as $row) {
    
        echo "$row->displayName : $row->username\n </br>";
    }
    
} catch (MongoDB\Driver\Exception\Exception $e) {

    $filename = basename(__FILE__);
    
    echo "The $filename script has experienced an error.\n"; 
    echo "It failed with the following exception:\n";
    
    echo "Exception:", $e->getMessage(), "\n";
    echo "In file:", $e->getFile(), "\n";
    echo "On line:", $e->getLine(), "\n";       
}

?>